import streamlit as st
import pandas as pd
import plotly.graph_objects as go

st.set_page_config(page_title="Forecast Explorer", page_icon="📈", layout="wide")

st.title("📈 Forecast Explorer")
st.caption("Page 2 of 4 — Forecasts generated by Prophet (the best-performing model from Task 3: "
           "lowest RMSE among SARIMA, Prophet, and XGBoost, with built-in seasonality that avoids "
           "large peak-month misses).")


@st.cache_data
def load_forecasts():
    fc = pd.read_csv("data/forecasts.csv")
    fc["Month"] = pd.to_datetime(fc["Month"])
    metrics = pd.read_csv("data/forecast_metrics.csv")
    return fc, metrics


forecast_df, metrics_df = load_forecasts()

# ---------------------------------------------------------------------------
# Controls
# ---------------------------------------------------------------------------
col1, col2 = st.columns([2, 2])

with col1:
    segment = st.selectbox(
        "Select Category or Region",
        options=forecast_df["Segment"].unique(),
        index=0,
        help="Choose a product category, a region, or 'Overall' for total company sales."
    )

with col2:
    horizon = st.slider(
        "Forecast horizon (months ahead)",
        min_value=1, max_value=3, value=3,
        help="How many months of the Jan-Mar 2019 forecast to display."
    )

st.divider()

# ---------------------------------------------------------------------------
# Chart: last 6 months actual + N months forecast
# ---------------------------------------------------------------------------
seg_data = forecast_df[forecast_df["Segment"] == segment].sort_values("Month")
actual = seg_data[seg_data["Type"] == "Actual"].tail(6)
forecast = seg_data[seg_data["Type"] == "Forecast"].head(horizon)

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=actual["Month"], y=actual["Value"], mode="lines+markers",
    name="Actual (last 6 months)", line=dict(color="#1f77b4", width=3)
))
fig.add_trace(go.Scatter(
    x=forecast["Month"], y=forecast["Value"], mode="lines+markers",
    name=f"Prophet Forecast ({horizon}mo ahead)", line=dict(color="#d62728", width=3, dash="dash")
))
# connect the two lines visually
if not actual.empty and not forecast.empty:
    fig.add_trace(go.Scatter(
        x=[actual["Month"].iloc[-1], forecast["Month"].iloc[0]],
        y=[actual["Value"].iloc[-1], forecast["Value"].iloc[0]],
        mode="lines", line=dict(color="#d62728", width=3, dash="dash"), showlegend=False
    ))

fig.update_layout(
    title=f"{segment} — Actual vs Forecasted Monthly Sales",
    xaxis_title="Month", yaxis_title="Sales ($)",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)
st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------------------------
# Forecast table
# ---------------------------------------------------------------------------
st.subheader(f"Forecast values — next {horizon} month(s)")
display_fc = forecast.copy()
display_fc["Month"] = display_fc["Month"].dt.strftime("%B %Y")
display_fc["Value"] = display_fc["Value"].map(lambda v: f"${v:,.2f}")
st.dataframe(display_fc[["Month", "Value"]].rename(columns={"Value": "Forecasted Sales"}),
             use_container_width=True, hide_index=True)

st.divider()

# ---------------------------------------------------------------------------
# MAE / RMSE for this segment's model
# ---------------------------------------------------------------------------
st.subheader("Model Accuracy (backtested on held-out Oct–Dec 2018)")
seg_metrics = metrics_df[metrics_df["Segment"] == segment].iloc[0]

m1, m2, m3 = st.columns(3)
m1.metric("MAE", f"${seg_metrics['MAE']:,.2f}")
m2.metric("RMSE", f"${seg_metrics['RMSE']:,.2f}")
m3.metric("MAPE", f"{seg_metrics['MAPE']:.2f}%")

st.caption(
    "These accuracy metrics come from a genuine held-out test: the model was trained only on data "
    "before October 2018 and evaluated against the real Oct-Dec 2018 sales it had never seen — the "
    "same methodology used in Task 3/4 of the analysis notebook."
)
